# controllers/incident_controller.py
from agents.agent_pipeline import AgentPipeline
from services.jira_service import JiraService
from config import Config
import traceback
import os

class IncidentController:
    """
    Thin orchestrator — calls AgentPipeline and handles Jira posting.
    """

    def __init__(self):
        self.pipeline     = AgentPipeline()
        self.jira_service = JiraService()

    def process_incident(self, ticket_key):
        try:
            print(f"\nFetching ticket {ticket_key} from Jira...")
            ticket = self.jira_service.get_ticket(ticket_key)

            if not ticket:
                return {
                    'success': False,
                    'error':   f'Ticket {ticket_key} not found in Jira'
                }

            print(f"Running agent pipeline for {ticket_key}...")
            result = self.pipeline.run(ticket)

            # Post validated checklist to Jira as a comment
            try:
                checklist_text = result.get('validated_checklist_text', '')
                if checklist_text:
                    self.jira_service.post_comment(ticket_key, checklist_text)
                    print(f"Checklist posted to Jira {ticket_key}")
            except Exception as jira_err:
                print(f"Warning: Could not post to Jira: {jira_err}")

            # Save checklist locally
            try:
                self._save_checklist(ticket_key, result.get('validated_checklist_text', ''))
            except Exception as save_err:
                print(f"Warning: Could not save checklist file: {save_err}")

            return self._build_response(result, ticket_key, ticket)

        except Exception as e:
            traceback.print_exc()
            print(f"FULL ERROR: {str(e)}")
            return {'success': False, 'error': str(e)}

    def mark_resolved(self, ticket_key, completed_steps, mode):
        try:
            mode_label = "Manual Execution" if mode == "manual" else "Auto Execution"
            jira_comment = (
                f"✅ *Incident Resolved — {mode_label}*\n\n"
                f"- *Steps completed:* {len(completed_steps)}\n"
                f"- *Mode:* {mode_label}\n\n"
                f"_Resolved via AI Incident Management Agent (Agent 4)_"
            )
            self.jira_service.post_comment(ticket_key, jira_comment)
            self.jira_service.resolve_ticket(ticket_key)
            return {
                'success':    True,
                'message':    f'Ticket {ticket_key} marked as Completed in Jira',
                'ticket_key': ticket_key
            }
        except Exception as e:
            traceback.print_exc()
            return {'success': False, 'error': str(e)}

    def mark_script_generated(self, ticket_key):
        try:
            jira_comment = (
                f"📄 *Resolution Script Generated*\n\n"
                f"- Engineer downloaded `resolve_{ticket_key}.sh`\n"
                f"- Ticket will be resolved after script execution.\n\n"
                f"_Generated by AI Incident Management Agent (Agent 4)_"
            )
            self.jira_service.post_comment(ticket_key, jira_comment)
            return {'success': True, 'message': f'Script noted on {ticket_key}'}
        except Exception as e:
            return {'success': False, 'error': str(e)}

    def _save_checklist(self, ticket_key, checklist_text):
        filename = f"checklist_{ticket_key}.txt"
        with open(filename, 'w', encoding='utf-8') as f:
            f.write(checklist_text)
        print(f"Checklist saved to {filename}")

    def _build_response(self, pipeline_result, ticket_key, ticket):
        """Build the JSON response for React"""

        # Agent 3 output is the top-level result from pipeline
        validated_steps    = pipeline_result.get('validated_steps', [])
        validation_summary = pipeline_result.get('validation_summary', '')
        changes_made       = pipeline_result.get('changes_made', [])

        # Agent 2 output is nested inside original_output
        agent2_output    = pipeline_result.get('original_output', {})
        match_type       = agent2_output.get('match_type', 'no_match')
        matched_runbooks = agent2_output.get('matched_runbooks', [])

        base = {
            'success':            match_type != 'no_match',
            'ticket':             ticket,
            'full_checklist':     validated_steps,
            'validation_summary': validation_summary,
            'changes_made':       changes_made,
            'jira_url':           f"{Config.JIRA_SERVER}/browse/{ticket_key}"
        }

        if match_type == 'no_match':
            return {
                **base,
                'no_runbook_match':  True,
                'generic_checklist': validated_steps
            }
        elif match_type == 'single':
            runbook = matched_runbooks[0] if matched_runbooks else {}
            return {
                **base,
                'runbook':           runbook,
                'one_line_solution': (
                    f"Matched: {runbook.get('title', 'Unknown')} "
                    f"(Confidence: {runbook.get('confidence', 'N/A')}%)"
                )
            }
        else:  # multiple
            return {
                **base,
                'multiple_matches':  True,
                'matched_runbooks':  matched_runbooks,
                'combined_solution': f"Matched {len(matched_runbooks)} runbooks: "
                                     + ', '.join(rb.get('title', '') for rb in matched_runbooks)
            }