from langchain_core.prompts import PromptTemplate
from langchain_huggingface import HuggingFaceEndpoint
from config import Config


class ChecklistAgent:

    def __init__(self):

        self.llm = HuggingFaceEndpoint(
            repo_id=Config.MODEL_NAME,
            huggingfacehub_api_token=Config.HUGGINGFACE_API_KEY,
            temperature=0.3,
            max_new_tokens=600
        )

        self.prompt = PromptTemplate(
            input_variables=[
                "ticket_summary",
                "ticket_description",
                "runbook_title",
                "runbook_steps"
            ],
            template="""You are an IT incident response expert.

A Jira incident ticket has been received:
Ticket Summary: {ticket_summary}
Ticket Description: {ticket_description}

The most relevant runbook is: {runbook_title}

Reference runbook steps:
{runbook_steps}

Using the ticket details and the runbook above, generate a personalised 
resolution checklist. Replace any generic placeholders with specific values 
from the ticket (e.g. actual service names, database names, error codes).

Return ONLY a numbered list of steps. Maximum 8 steps. Be concise.
Each step should be: Step number. Action to take.

Checklist:"""
        )

        # pipeline
        self.chain = self.prompt | self.llm

    def run(self, agent1_output):

        match_type = agent1_output['match_type']
        matched_runbooks = agent1_output['matched_runbooks']
        ticket = agent1_output['ticket_context']

        print(f"\n[Agent 2] Generating checklist. Match type: {match_type}")

        if match_type == 'no_match':
            return self._generate_ai_only(ticket)

        primary_runbook = matched_runbooks[0]

        result = self.chain.invoke({
            "ticket_summary": ticket['summary'],
            "ticket_description": ticket.get('description', ''),
            "runbook_title": primary_runbook['title'],
            "runbook_steps": primary_runbook['steps'][:1000]
        })

        raw_output = result.strip()

        steps_list = self._parse_steps(raw_output)

        checklist_text = self._format_for_jira(
            ticket,
            primary_runbook,
            steps_list,
            matched_runbooks
        )

        print(f"[Agent 2] Generated {len(steps_list)} steps")

        return {
            'checklist_text': checklist_text,
            'checklist_steps': steps_list,
            'runbook_title': primary_runbook['title'],
            'match_type': match_type,
            'matched_runbooks': matched_runbooks,
            'ticket_context': ticket
        }

    def _generate_ai_only(self, ticket):

        no_match_prompt = PromptTemplate(
            input_variables=["ticket_summary", "ticket_description"],
            template="""You are an IT incident response expert.

A Jira incident ticket has been received with no matching runbook:
Summary: {ticket_summary}
Description: {ticket_description}

Generate a generic troubleshooting checklist for this incident.
Return ONLY a numbered list. Maximum 6 steps. Be concise.

Checklist:"""
        )

        chain = no_match_prompt | self.llm

        result = chain.invoke({
            "ticket_summary": ticket['summary'],
            "ticket_description": ticket.get('description', '')
        })

        steps_list = self._parse_steps(result.strip())
        checklist_text = self._format_no_match(ticket, steps_list)

        return {
            'checklist_text': checklist_text,
            'checklist_steps': steps_list,
            'runbook_title': None,
            'match_type': 'no_match',
            'matched_runbooks': [],
            'ticket_context': ticket
        }

    def _parse_steps(self, raw_text):

        steps = []

        for line in raw_text.split('\n'):
            line = line.strip()

            if line and line[0].isdigit():

                if '. ' in line:
                    steps.append(line.split('. ', 1)[1].strip())

                elif ') ' in line:
                    steps.append(line.split(') ', 1)[1].strip())

        return steps if steps else [raw_text]

    def _format_for_jira(self, ticket, runbook, steps, all_matches):

        steps_text = '\n'.join(f"# {step}" for step in steps)

        confidence = runbook.get('confidence', 'N/A')

        return f"""h2. AI Incident Resolution Checklist

*Ticket:* {ticket['key']} — {ticket['summary']}
*Matched Runbook:* {runbook['title']} (Confidence: {confidence}%)

h3. Resolution Steps
{steps_text}

h3. Validation
* [] Confirm incident is resolved
* [] Monitor for 5 minutes

_Generated by AI Incident Management Agent (Agent 2 — Checklist Generator)_"""

    def _format_no_match(self, ticket, steps):

        steps_text = '\n'.join(f"# {step}" for step in steps)

        return f"""h2. AI-Generated Incident Checklist (No Runbook Match)

*Ticket:* {ticket['key']} — {ticket['summary']}
*Note:* No matching runbook found. Steps generated by AI.

h3. Suggested Steps
{steps_text}

_Generated by AI Incident Management Agent (Agent 2 — AI Fallback)_"""